### ISSUE TITLE
Error when publishing changes in the apps / content project from workspc to the local AEM instance 

### ISSUE THREAD

**Issue by navp4l** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#1]
I repeatedly get the below error when trying to publish the apps or the content projects to the AEM server

[23 August, 2014 10:11:04 PM IST] AddOrUpdateNodeCommand -> /apps/example/tests : JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.nodetype.ConstraintViolationException: no matching property definition found for {}dependencies](39 ms)
org.apache.sling.ide.transport.RepositoryException: javax.jcr.nodetype.ConstraintViolationException: no matching property definition found for {}dependencies
    at org.apache.sling.ide.impl.vlt.JcrResult.failure(JcrResult.java:33)
    at org.apache.sling.ide.impl.vlt.JcrCommand.execute(JcrCommand.java:65)
    at org.apache.sling.ide.transport.TracingCommand.execute(TracingCommand.java:43)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.execute(SlingLaunchpadBehaviour.java:455)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishContentModule(SlingLaunchpadBehaviour.java:428)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:231)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1091)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1183)
    at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
    at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
    at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3157)
    at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: javax.jcr.nodetype.ConstraintViolationException: no matching property definition found for {}dependencies
    at org.apache.jackrabbit.jcr2spi.nodetype.ItemDefinitionProviderImpl.getQPropertyDefinition(ItemDefinitionProviderImpl.java:233)
    at org.apache.jackrabbit.jcr2spi.nodetype.ItemDefinitionProviderImpl.getQPropertyDefinition(ItemDefinitionProviderImpl.java:126)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.getApplicablePropertyDefinition(NodeImpl.java:1831)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.createProperty(NodeImpl.java:1518)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.setProperty(NodeImpl.java:252)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.setProperty(NodeImpl.java:232)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.updateNode(AddOrUpdateNodeCommand.java:299)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.update(AddOrUpdateNodeCommand.java:99)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.execute0(AddOrUpdateNodeCommand.java:80)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.execute0(AddOrUpdateNodeCommand.java:1)
    at org.apache.sling.ide.impl.vlt.JcrCommand.execute(JcrCommand.java:57)
    ... 12 more
[23 August, 2014 10:11:04 PM IST] AddOrUpdateNodeCommand -> /content/example : JcrResult[ success:true](159 ms)
[23 August, 2014 10:11:04 PM IST] AddOrUpdateNodeCommand -> /content/dam/example : JcrResult[ success:true](143 ms)
[23 August, 2014 10:11:04 PM IST] AddOrUpdateNodeCommand -> /content/example : JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.RepositoryException: Unable to retrieve definition for item with id '/content/example/jcr:content'.](70 ms)
org.apache.sling.ide.transport.RepositoryException: javax.jcr.RepositoryException: Unable to retrieve definition for item with id '/content/example/jcr:content'.
    at org.apache.sling.ide.impl.vlt.JcrResult.failure(JcrResult.java:33)
    at org.apache.sling.ide.impl.vlt.JcrCommand.execute(JcrCommand.java:65)
    at org.apache.sling.ide.transport.TracingCommand.execute(TracingCommand.java:43)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.execute(SlingLaunchpadBehaviour.java:455)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishContentModule(SlingLaunchpadBehaviour.java:428)
    at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:231)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1091)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1183)
    at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
    at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
    at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
    at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3157)
    at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: javax.jcr.RepositoryException: Unable to retrieve definition for item with id '/content/example/jcr:content'.
    at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl.getItemDefinition(RepositoryServiceImpl.java:954)
    at org.apache.jackrabbit.spi2dav.RepositoryServiceImpl.getNodeDefinition(RepositoryServiceImpl.java:893)
    at org.apache.jackrabbit.jcr2spi.nodetype.ItemDefinitionProviderImpl.getNodeDefinition(ItemDefinitionProviderImpl.java:350)
    at org.apache.jackrabbit.jcr2spi.nodetype.ItemDefinitionProviderImpl.getQNodeDefinition(ItemDefinitionProviderImpl.java:81)
    at org.apache.jackrabbit.jcr2spi.state.NodeState.retrieveDefinition(NodeState.java:467)
    at org.apache.jackrabbit.jcr2spi.state.NodeState.getDefinition(NodeState.java:316)
    at org.apache.jackrabbit.jcr2spi.state.ItemStateValidator.checkProtection(ItemStateValidator.java:504)
    at org.apache.jackrabbit.jcr2spi.state.ItemStateValidator.checkIsWritable(ItemStateValidator.java:214)
    at org.apache.jackrabbit.jcr2spi.state.ItemStateValidator.checkWriteProperty(ItemStateValidator.java:313)
    at org.apache.jackrabbit.jcr2spi.state.ItemStateValidator.checkSetProperty(ItemStateValidator.java:253)
    at org.apache.jackrabbit.jcr2spi.state.SessionItemStateManager.setPropertyStateValue(SessionItemStateManager.java:516)
    at org.apache.jackrabbit.jcr2spi.state.SessionItemStateManager.visit(SessionItemStateManager.java:381)
    at org.apache.jackrabbit.jcr2spi.operation.SetPropertyValue.accept(SetPropertyValue.java:82)
    at org.apache.jackrabbit.jcr2spi.state.SessionItemStateManager.execute(SessionItemStateManager.java:215)
    at org.apache.jackrabbit.jcr2spi.PropertyImpl.setInternalValues(PropertyImpl.java:609)
    at org.apache.jackrabbit.jcr2spi.PropertyImpl.setValue(PropertyImpl.java:590)
    at org.apache.jackrabbit.jcr2spi.PropertyImpl.setValue(PropertyImpl.java:110)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.setProperty(NodeImpl.java:246)
    at org.apache.jackrabbit.jcr2spi.NodeImpl.setProperty(NodeImpl.java:232)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.updateNode(AddOrUpdateNodeCommand.java:299)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.update(AddOrUpdateNodeCommand.java:99)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.update(AddOrUpdateNodeCommand.java:103)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.execute0(AddOrUpdateNodeCommand.java:80)
    at org.apache.sling.ide.impl.vlt.AddOrUpdateNodeCommand.execute0(AddOrUpdateNodeCommand.java:1)
    at org.apache.sling.ide.impl.vlt.JcrCommand.execute(JcrCommand.java:57)
    ... 12 more

I did raise a query on the help forums but didn't really get a resolution,

http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.topic.1.html/forum__2svm-did_anyone_haveany.html

**Comment by priyaAEM** [comment]
Hi Rombert,

I am still facing this issue after creating a fresh AEM Multi Module project.

Issue 1) Failed publishing path=/content/dam/diginova, result=JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.ReferentialIntegrityException: OakIntegrity0001: Unable to delete referenced node]
Issue 2) Exception Trace:
org.apache.sling.ide.eclipse-core
Error
Sun Oct 25 11:37:44 IST 2015
Failed installing bundle : Method execution returned status 500

org.apache.sling.ide.osgi.OsgiClientException: Method execution returned status 500
at org.apache.sling.ide.osgi.impl.HttpOsgiClient$LocalBundleInstaller.installBundle(HttpOsgiClient.java:221)
at org.apache.sling.ide.osgi.impl.HttpOsgiClient.installLocalBundle(HttpOsgiClient.java:172)
at org.apache.sling.ide.osgi.impl.TracingOsgiClient.logInstallLocalBundle(TracingOsgiClient.java:75)
at org.apache.sling.ide.osgi.impl.TracingOsgiClient.installLocalBundle(TracingOsgiClient.java:57)
at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishBundleModule(SlingLaunchpadBehaviour.java:341)
at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:221)
at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1091)
at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1183)
at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3157)
at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

 Any help is much appreciated.

**Comment by rombert** [comment]
@priyaAEM - can you please open a new bug and let me know what versions of 

- AEM Developer Tools
- Sling IDE Tooling 

you have installed?

**Comment by esaiventhan** [comment]
Just to add a note on this, I faced a similar issue. I saw a software update notice in my Eclipse alert message, and once I updated it fully (which also asked me to restart the IDE) - I could see no error. All works fine now.
