### ISSUE TITLE
AEM Eclipse Plugin: AEM Bundle(core module) not getting published

### ISSUE THREAD

**Issue by Ketki17** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#71]
Hi ,

I have been in AEM Developer tool , I followed the exact procedure given in this forum "https://docs.adobe.com/docs/en/dev-tools/aem-eclipse.html" but when I am trying to publish it to AEM Repository it giving me the following error:

Failed installing bundle: Method Execution returned status 500.

I am using following version:

Eclipse Luna SR2 (4.4.2)
Java: 1.7
AEM 6.1

**Comment by rombert** [comment]
Do you have anything in the AEM error.log that can be linked to the installation erors?

**Comment by Ketki17** [comment]
Hi,

I am getting this error logged in error log file of AEM .

javax.jcr.nodetype.ConstraintViolationException: No default node type available for /system/sling/tooling
	at org.apache.jackrabbit.oak.util.TreeUtil.addChild(TreeUtil.java:186)
	at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.addChild(NodeDelegate.java:692)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:290)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:257)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:216)
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:113)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:257)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:242)


Is it related to the eclipse plugin?

**Comment by Ketki17** [comment]
DO I need to install any other software in eclipse to get the things work?

Thanks

**Comment by rombert** [comment]
Looks like you don't have the Apache Sling Tooling Support Install bundle installed, but it should be installed automatically.

What version of the AEM Developer Tools are you using?

**Comment by Ketki17** [comment]
Hi ,

Please refer attached file for the version 
![versions](https://cloud.githubusercontent.com/assets/6203403/15392544/5a897a20-1de5-11e6-8faa-fada99ed61bb.png)

And I check the Web Console also Apache Sling Tooling Support Install bundle is also installed ..
see this image file
![slingtool](https://cloud.githubusercontent.com/assets/6203403/15392592/a07ec4f4-1de5-11e6-94f5-c79f07bab1b2.png)

**Comment by rombert** [comment]
Interesting that the bundle did not start. Can you try starting it from the Web Console? If it fails, what does it print in the error.log?

**Comment by Ketki17** [comment]
Yes I was about to ask you the same thing .

It is throwing this error ..

*ERROR* [qtp1759696269-245] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.sling.tooling.support.install [448]: Unable to resolve 448.27: missing requirement [448.27] osgi.wiring.package; (osgi.wiring.package=javax.servlet))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.apache.sling.tooling.support.install [448]: Unable to resolve 448.27: missing requirement [448.27] osgi.wiring.package; (osgi.wiring.package=javax.servlet)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964)
	at org.apache.felix.webconsole.internal.core.BundlesServlet.doPost(BundlesServlet.java:365)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:555)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager$3.run(OsgiManager.java:459)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:455)
	at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:336)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:297)
	at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:93)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:50)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)
	at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.doHandle(FilterHandler.java:108)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:80)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:46)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:31)
	at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308)

**Comment by rombert** [comment]
That is really weird ... `(osgi.wiring.package=javax.servlet)` should be satisfiable since you have Jetty running.

Is AEM launched from the quickstart or from a WAR file? Have you applied any customisations ( removed/added bundles/content packages)?

**Comment by Ketki17** [comment]
Nope i have not done any custimisations, I tried deleting sling tooling install bundle and reinstall it (downloaded bundle from "https://sling.apache.org/downloads.cgi") and it worked.

Thanks for the support :)

**Comment by rombert** [comment]
Glad to hear that it works now :-)
