### ISSUE TITLE
New projects are created in a broken state

### ISSUE THREAD

**Issue by re-jim** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#75]
Probably the same as https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/issues/72

I'm using Eclipse 4.5.2

Maven Apache Maven 3.2.5 
Java version: 1.8
Windows 10

Here are my relevant plugins

![image](https://cloud.githubusercontent.com/assets/22106884/18402432/8f67b1f2-769c-11e6-9647-d3e88e18cb32.png)

When I create a new AEM Sample Multi-Module Project, selecting Archetype 10, I get an error saying "Failed while installing Sightly 1.1"

![image](https://cloud.githubusercontent.com/assets/22106884/18402587/608bb062-769d-11e6-9230-9e3d4684b365.png)

If I choose not to immediately deploy them on a server I just get "Problems encountered while setting project description" with the same four errors.

![image](https://cloud.githubusercontent.com/assets/22106884/18403281/0bcf3bb2-76a1-11e6-8cd6-0a980c77e3ce.png)

Those four errors in the "Problems" space are:

```

Description Resource    Path    Location    Type
C:\Users\Owner\aem\example\it.tests\src\main\java\org\myorg\example\it\tests\HelloWorldModelServerSideTest.java : Unable to load compiled class: org.myorg.example.it.tests.HelloWorldModelServerSideTest (org.apache.felix:maven-scr-plugin:1.20.0:scr:generate-scr-scrdescriptor:process-classes)

org.apache.maven.plugin.MojoExecutionException: C:\Users\Owner\aem\example\it.tests\src\main\java\org\myorg\example\it\tests\HelloWorldModelServerSideTest.java : Unable to load compiled class: org.myorg.example.it.tests.HelloWorldModelServerSideTest
    at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:249)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
    at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
    at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.felix.scrplugin.SCRDescriptorException: Unable to load compiled class: org.myorg.example.it.tests.HelloWorldModelServerSideTest
    at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:148)
    at org.apache.felix.scrplugin.SCRDescriptorGenerator.execute(SCRDescriptorGenerator.java:146)
    at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:237)
    ... 32 more
Caused by: java.lang.ClassNotFoundException: org.myorg.example.it.tests.HelloWorldModelServerSideTest
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:144)
    ... 34 more
    pom.xml /example.it.tests   line 23 Maven Build Problem
Project configuration is not up-to-date with pom.xml. Select: Maven->Update Project... from the project context menu or use Quick Fix.  example.it.launcher     line 1  Maven Configuration Problem
Project configuration is not up-to-date with pom.xml. Select: Maven->Update Project... from the project context menu or use Quick Fix.  example.it.tests        line 1  Maven Configuration Problem
Project configuration is not up-to-date with pom.xml. Select: Maven->Update Project... from the project context menu or use Quick Fix.  example.ui.apps     line 1  Maven Configuration Problem

```

**Comment by Millertaker** [comment]
yeah the same, i think the plugin has the problem, if you clic cancel and then run a build from console, will work. I'm looking it now and its making changes when i publish. I not able yet to run the debug mode 

<img width="1434" alt="screen shot 2016-09-09 at 4 21 02 pm" src="https://cloud.githubusercontent.com/assets/2975617/18403294/7da62680-76a9-11e6-9b89-6c082a10a98d.png">

**Comment by re-jim** [comment]
@Millertaker, How do you run a build from console?

**Comment by Millertaker** [comment]
go to root of your project and run the maven command:  ` mvn -PautoInstallPackage -PintegrationServer install `

**Comment by re-jim** [comment]
After doing that I get six successes, and a warning that " The requested profile "integrationServer" could not be activated because it does not exist."

The launcher, tests, and apps folders still have errors associated with them, and I cannot add these resources to the server.

**Comment by Millertaker** [comment]
try create all project through maven with this: 

``` 
mvn archetype:generate -DarchetypeRepository=http://repo.adobe.com/nexus/content/groups/public/ -DarchetypeGroupId=com.day.jcr.vault -DarchetypeArtifactId=multimodule-content-package-archetype -DarchetypeVersion=1.0.2 -DgroupId=com.adobe.cq -DartifactId=key61 -Dversion=1.0-SNAPSHOT -Dpackage=com.adobe.cq -DappsFolderName=myproject -DartifactName="My Project" -DcqVersion="5.6.1" -DpackageGroup="My Company"
```

and import it as a maven prj on eclipse. Should be work as if you have created through  the wizard.

**Comment by re-jim** [comment]
When I run that command and import the project as a maven project in Eclipse, I get this error from pom.xml:

cvc-elt.1: Cannot find the declaration of element 'project'.

I deleted a trailing space inside of xsi:schemaLocation and that fixed it.
This also doesn't provide all of the dependencies I get when creating a project through the wizard, but when I deploy it, it seems to work.

**Comment by midnit** [comment]
@Millertaker - @re-jim is using Archetype 10, why would you instruct him to generate a new project with an extremely outdated archetype version? :anguished:

**Comment by tamipangadil** [comment]
Hi @re-jim,

I've also experienced this kind of problem. You just need to delete all your Maven repositories and try to create project again and it will be fine.

The main reason is the packages in your Maven repository could be corrupted. Maybe when it tries to download you have weak or intermittent connection. 

Let me know if it works.

**Comment by rombert** [comment]
Looks to be the same issue as #72  - let's continue the discussion there.
